-- AlterTable
ALTER TABLE "Route" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "destination" TEXT,
ADD COLUMN     "origin" TEXT,
ALTER COLUMN "startAt" DROP NOT NULL,
ALTER COLUMN "finishAt" DROP NOT NULL;
